
import { Geist, Geist_Mono, Raleway } from "next/font/google";
import "./globals.css";
import "./index.css"
import Sidebar from "@/components/Sidebar";
import { ThemeProvider } from "@/components/theme-provider"
import { AuthProvider } from "@/context/AuthContext";
import AleartMessage from "@/components/AleartMessage";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"]
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "TasteMe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {




  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased`}
      >
        <AuthProvider>
          <AleartMessage />
          {/* <Sidebar /> */}
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >

            {children}
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
